version: '3.8'

services:

  # PostgreSQL database container with PostGIS
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres-container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL
    networks:
      - app-network

  yoonic_api:
    build: .
    container_name: yoonic_api-container
    ports:
      - 8000:8000  # Exposes API on port 8000
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}  # Points to the postgres service
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - DATABASE_URL=postgresql://postgres:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/${DATABASE_NAME}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - DOMAIN=${DOMAIN}
      - EMAIL_CODE_EXPIRE_MINUTES=${EMAIL_CODE_EXPIRE_MINUTES}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - NOMINATIM_BASE_URL=${NOMINATIM_BASE_URL}
      - USER_AGENT=${USER_AGENT}
    networks:
      - app-network
    depends_on:
      - postgres
    command: >
      bash -c "alembic upgrade heads && uvicorn app.main:app --host 0.0.0.0 --port 8000"

networks:
  app-network:
    driver: bridge

# Persistent volume to store PostgreSQL data
volumes:
  postgres_data: