apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: fastapi-namespace
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: fastapi
  loadBalancerIP: 192.168.1.200
