name: QA checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DATABASE_HOSTNAME: test_host
      DATABASE_PORT: 1234
      DATABASE_USERNAME: test_user
      DATABASE_PASSWORD: test_pwd
      DATABASE_NAME: test
      SECRET_KEY: 73283481248249276gsdhvsjdv8734243fsasf4t2245t54544564sd
      REFRESH_SECRET_KEY: 09d25e094faa6c3453434f818166b7a9563b943434499f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 40
      EMAIL: test@gmail.com
      EMAIL_PASSWORD: test_pwd
      SMTP_SERVER: smtp.email.com
      SMTP_PORT: 123
      DOMAIN: url_path
      EMAIL_CODE_EXPIRE_MINUTES: 30
      GOOGLE_APPLICATION_CREDENTIALS: "test_file"
      NOMINATIM_BASE_URL: "http://test"
      USER_AGENT: "test"


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requeriments.txt

    - name: Run tests with pytest
      run: |
        pytest -v --maxfail=1 --disable-warnings
